# Generated by Django 3.1.2 on 2020-12-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201206_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.CharField(max_length=299, unique=True),
        ),
    ]
