# Generated by Django 3.1.2 on 2020-12-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201213_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
