# Generated by Django 3.1.4 on 2021-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='name',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
