# Generated by Django 3.1.4 on 2021-05-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210305_1118'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductView',
            new_name='ProductImages',
        ),
    ]
